---
- name: install consul server
  hosts: all
  serial: 1
  become: true

  vars:
    CONSUL_VERSION: "1.6.2"
    CONSUL_LICENSE: ""
    CONSUL_GOSSIP_ENCRYPTION_KEY: ""
    NODE_NAME: "Consul-Server"
    CONSUL_DATA_PATH: "/var/consul/data"
    ADVERTISE_ADDR: "127.0.0.1"
    JOIN_TAG: "my-cluster"
    RETRY_JOIN: "provider=aws tag_key=Consul tag_value={{ JOIN_TAG }}" 
    ZONE: "my-zone"
    BOOTSTRAP_EXPECT: 1
    CONSUL_INITIAL_MANAGEMENT_TOKEN: ""

  tasks:

  - name: install epel-release
    yum:
      name: epel-release
      state: present

  - name: install common packages
    yum:
      name:
        - unzip
        - vim
        - jq
        - bind-utils
      state: present

  - name: download binary
    unarchive:
      src: "https://releases.hashicorp.com/consul/{{ CONSUL_VERSION }}/consul_{{ CONSUL_VERSION }}_linux_amd64.zip"
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Add the system user 'consul'
    user:
      name: consul
      home: /etc/consul.d
      shell: /bin/false
      system: yes

  - name: create data directory
    file: 
      path: /var/consul/data
      state: directory
      recurse: yes
      owner: consul
      group: consul

  - name: create config directory
    file: 
      path: /etc/consul.d/
      state: directory
      recurse: yes
      owner: consul
      group: consul

  - name: configure env file
    template:
      src: ./files/consul-env.conf.j2
      dest: /etc/consul.d/env.conf
      mode: 0640
      owner: consul
      group: consul

  - name: create ca file
    template:
      src: ./files/consul-agent-ca.pem
      dest: /etc/consul.d/consul-agent-ca.pem
      mode: 0640
      owner: consul
      group: consul

  - name: create key file
    template:
      src: ./files/consul-agent-ca-key.pem
      dest: /etc/consul.d/consul-agent-ca-key.pem
      mode: 0640
      owner: consul
      group: consul

  - name: create server cert
    ansible.builtin.command:
      cmd: /usr/local/bin/consul tls cert create -server -node {{ NODE_NAME }} -dc dc1 -additional-dnsname {{ NODE_NAME }}.dc1.consul -additional-dnsname server.dc1.consul -additional-ipaddress={{ ADVERTISE_ADDR}}
    become: yes
    become_user: consul
    args:
      chdir: /etc/consul.d/
      creates: /etc/consul.d/dc1-server-consul-0.pem

  - name: configure server
    template:
      src: ./files/consul-server.hcl.j2
      dest: /etc/consul.d/server.hcl
      mode: 0640
      owner: consul
      group: consul

  - name: configure systemd
    copy:
      src: ./files/consul-server.service
      dest: /etc/systemd/system/consul.service

  - name: start consul server
    systemd:
      name: consul.service
      state: restarted
      enabled: yes
      daemon_reload: yes